### ISSUE TITLE
Hermit should `sync` the manifests whenever it comes across a package version not in the local manifests

### ISSUE THREAD

**Issue by jvmakine** [cashapp/hermit#363]
When a user pulls changes from a remote repo, containing a recently released version of a package, they might get
```
no version ... found in versions ...
```
error.

Now the user needs to manually run
```
hermit sync
```
to get around this.

We should sync the manifests automatically when this happens to check for new versions.

**Comment by nickajacks1** [comment]
I would like to work on this. What would be a good way to reproduce this beside waiting for the next autoversion?

**Comment by nickajacks1** [comment]
Given a user with an out of date manifest (e.g., ABC v1.2.3 is the highest version that exists but user's manifest only contains up to v1.0.0)

- User activates hermit on a project containing ABC v.1.2.3:
  - `hermit list` does not show ABC at all ❌[1]
  - `hermit uninstall ABC` prints `package ABC is not installed` ❌[2]
  - running `ABC` syncs manifests, downloads, and runs ABC v1.2.3 as expected ✅

- User activates hermit on a project containing ABC v0.0.1
  - `hermit upgrade ABC` syncs manifests and upgrades ABC to v1.2.3 as expected ✅
- User runs `hermit install ABC` on a project without ABC installed, ABC v1.0.0 is installed ❓[3]

For [1], I'd expect ABC to be shown, perhaps with some note about an unknown version
For [2], I'd expect a more clear error message.  It's probably incorrect to uninstall anyway because the upstream manifest may specify on uninstall actions for that version. Maybe there should be a --force option just in case.
For [3], I'm not sure whether this behavior is ideal or not.  It's probably fine as-is.

@alecthomas  What do you think about [1] and [2]?

**Comment by alecthomas** [comment]
1 makes sense, but 2 should uninstall it from the repo. Uninstall hooks only act on the package in the shared cache, and (somewhat counterintuitively) "hermit uninstall" doesn't actually uninstall it from there.

I agree that `package ABC is not installed` is not a helpful error message
